apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nestjs-canary-demo
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - nestjs-canary.demo.com
