apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-deployer
  namespace: nestjs-canary-demo

#kubectl -n nestjs-canary-demo create rolebinding github-actions-deployer-edit --clusterrole=edit --serviceaccount=nestjs-canary-demo:github-actions-deployer --namespace=nestjs-canary-demo